import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { TooltipProvider } from "~/components/ui/tooltip";
import { Toaster } from "sonner";
import { Provider as ReactWrapBalancerProvider } from 'react-wrap-balancer'
import { Inter } from 'next/font/google'
import QueryClientProviderComponent from "~/components/providers/query-client"
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: "canvasly",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="w-full">
        <QueryClientProviderComponent>
          <ReactWrapBalancerProvider>
            <Toaster />
            <TooltipProvider>
              {children}
            </TooltipProvider>
          </ReactWrapBalancerProvider>
        </QueryClientProviderComponent>
      </body>
    </html>
  );
}
