import type { Metadata } from "next";
import { createClient } from "@/utils/supabase/server";
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area"
import { Flame, FlaskConical, Group, GroupIcon, HandCoins, Home, LayoutTemplate, Monitor, Plus, Presentation, Rss, Settings, ShieldAlert, Speech, Users2 } from "lucide-react";
import ThemeSwitch from "@/components/ThemeToggle";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import Link from "next/link";
import DndProvider from "@/components/DndProvider";
import PresentationSidebar from "@/components/PresentationSidebar";
import SidebarLink from "@/components/SidebarLink";
import DetailsSidebar, { Item } from "@/components/DetailsSidebar";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet"
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from "@/components/ui/drawer"
import { Button } from "@/components/ui/button";


export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let Items: Item[] = [{
    icon: <ShieldAlert />,
    link: "/dashboard/no-presentations",
    name: "no presentations"
  }] as Item[]
  const supabase = createClient()
  const user = await supabase.auth.getUser()
  const id = user.data.user?.id
  if (!id) throw new Error("Internal error, please try to sign in.")
  // fetch all Presentations
  const presentations = await supabase.from("presentation").select("*").eq("owner", id)
  if (presentations.data != null || undefined || "[]" || []) {
    console.log("existing")
    Items.splice(0, 1)
    console.log(Items.splice(0,1))
  } 
  presentations.data?.forEach((presentation) => {
    Items.push({
      name: presentation.title,
      icon: <Monitor />,
      link: `/dashboard/presentation/${presentation.id}`
    })
  })
  return (
    <div className="flex w-full h-screen bg-[#e0e0e0] dark:bg-[#111214]">
      {/* Sidebar */}
      <div className="w-[12%]">
        <DropdownMenu >
          <DropdownMenuTrigger className="my-2"><h3 className="mx-2 px-[10px]">canvasly</h3></DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuLabel>Canvasly</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <Link href={"/"}><DropdownMenuItem className="cursor-pointer">Homepage</DropdownMenuItem></Link>
            <DropdownMenuItem>Sign out</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>

        <div className="flex flex-col mx-2">
          <SidebarLink icon={<Home className="h-4 w-4" />} title="Home" link="/dashboard/" />
          <Drawer>
            <DrawerTrigger className="block md:hidden">
              <SidebarLink icon={<Settings className="h-4 w-4" />} title="Settings"  />
            </DrawerTrigger>
            <DrawerContent className="block md:hidden">
              <DrawerHeader>
                <DrawerTitle>Are you absolutely sure?</DrawerTitle>
                <DrawerDescription>This action cannot be undone.</DrawerDescription>
              </DrawerHeader>
              <DrawerFooter>
                <Button>Submit</Button>
                <DrawerClose>
                  <Button variant="outline">Cancel</Button>
                </DrawerClose>
              </DrawerFooter>
            </DrawerContent>
          </Drawer>
          <Sheet>
            <SheetTrigger className="hidden md:block">
              <SidebarLink icon={<Settings className="h-4 w-4" />} title="Settings"  />
            </SheetTrigger>
            <SheetContent>
              <SheetHeader>
                <h2 className="text-2xl">Settings</h2>
              </SheetHeader>
            </SheetContent>
          </Sheet>

          <SidebarLink icon={<Users2 className="h-4 w-4" />} title="Contacts" link="/dashboard/contacts/" />
          <SidebarLink icon={<Rss className="h-4 w-4" />} title="Updates" link="/dashboard/updates/" />
          <SidebarLink icon={<HandCoins className="h-4 w-4" />} title="Plan" link="/dashboard/plan/" />
          <SidebarLink icon={<LayoutTemplate className="h-4 w-4" />} title="Templates" link="/dashboard/templates/" />
          <SidebarLink icon={<Speech className="h-4 w-4" />} title="Feedback" link="/dashboard/feedback/" />
          <hr className="my-1" />
          <DetailsSidebar
            action={[
              { icon: (<Plus className="h-5 w-5" />), link: "/dashboard/new", tooltip: "new presentation" }
            ]}
            icon={<Presentation className="h-4 w-4" />} title="Presentations" items={Items} />
        </div>
      </div>
      <ScrollArea className="rounded-2xl border dark:border-[#ffffff0c] dark:hover:border-[#ffffff1f] transition duration-300  bg-[#141517] h-[calc(100vh - 16px)] m-2  w-full " id="scrollContainer">
        <DndProvider>
          {children}
        </DndProvider>
        <ScrollBar />
      </ScrollArea>
    </div>
  );
}
