import type { Metadata } from "next";
import { createClient } from "@/utils/supabase/server";
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area"
import { Toggle } from "@/components/ui/toggle";
import { Italic, Settings } from "lucide-react";
import ThemeSwitch from "@/components/ThemeToggle";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import Link from "next/link";
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createClient();
  const user = await supabase.auth.getUser();
  console.log(user || "no user")
  return (
    <div className="flex w-full h-screen bg-[#e0e0e0] dark:bg-[#101010]">
      {/* Sidebar */}
      <div className="w-[12%]">
        <div className="flex m-2 justify-between">
          <Avatar>
            <AvatarFallback className="h-10 w-10">
              he
            </AvatarFallback>
          </Avatar>
          <div className="flex items-center">
            <ThemeSwitch  />
            <Link href={"/dashboard/settings"}>
              <Settings  className="h-5 w-5 ml-1" />
            </Link>
          </div>
        </div>
      </div>
      <ScrollArea className="rounded-2xl border-[#808080]  bg-[#272727] dark:border-[#ffffffc0] h-[calc(100vh - 16px)] m-2  w-full " id="scrollContainer">
        {children}
        <ScrollBar />
      </ScrollArea>
    </div>
  );
}
