import type { Metadata } from "next";
import { supabase } from "@/config/supabase";
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await supabase.auth.getUser();
  console.log(user || "no user")
  return (
    <div>
      <div className="flex flex-col items-center">
        <div>
          <h2>
            {user?.data.user?.created_at}
          </h2>
        </div>

      </div>
      {children}
    </div>
  );
}
